apiVersion: apps/v1
kind: Deployment
metadata:
  name: new1-deployment
  labels:
    app: new1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: new1
  template:
    metadata:
      labels:
        app: new1
    spec:
      containers:
      - name: new1
        image: vmns/new1:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: new1-service
spec:
  selector:
    app: new1
  ports:
    - protocol: TCP
      port: 8080  # Exposed port on the Service
      targetPort: 8081  # Port inside the container (Tomcat)
  type: LoadBalancer  # External acces
